.gitignore

Added `.gitignore` to ignore some files from being tracked.

Added .gitignore 

---

pyfocal/core/data.py
pyfocal/interfaces/default_loaders/ascii.yaml
pyfocal/interfaces/loaders.py

Added ASCII loader (see #19). Added user-defined dispersion unit to `Data` (spectrum object).

Added ASCII loader

---

docs/source/installation.rst
docs/source/introduction.rst
docs/source/model_fitting.rst

Added text to introduction. Fixed some doc ref names.

Added text to introduction

---

docs/source/custom_loaders.rst
docs/source/index.rst

Added text for custom loaders.

Added text for custom loaders

---

docs/source/api/index.rst
docs/source/conf.py
docs/source/custom_loaders.rst
pyfocal/core/data.py

Fix API doc and math formula. Corrected verbiage for data layers.

Minor doc fixes

---

pyfocal/core/containers.py
pyfocal/ui/controller.py
pyfocal/ui/qt/uic/source/mainwindow.ui
pyfocal/ui/qt/uic/source/pyfocal.pro.user
pyfocal/ui/viewer.py
pyfocal/ui/widgets/plot_window.py

This PR includes
* The ability to show/hide layers via exposed check box
* A fix to prevent crashing when hitting the "Create" button with no models

Layer visibility toggle

---

pyfocal/analysis/modeling.py
pyfocal/interfaces/managers.py
pyfocal/ui/controller.py
pyfocal/ui/viewer.py

This PR tackles
* #67 - model order is now correct between internal models and arithmetic expression variables
* #65 - no more crashing on fitting of models to data (for Gaussian and many others)
* #11 - model list names no longer reset and are persistent

Miscellaneous model improvements

---

docs/source/conf.py
docs/source/model_fitting.rst
pyfocal/analysis/statistics.py

Fixed doc intersphinx linking and added arith text

Fixed doc intersphinx linking and added arith text

---

docs/source/api/index.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/model_fitting.rst

Fixes #78 -- RTD left menu too crowded.
Updated arithmetic box doc as per #74.

More doc updates

---

pyfocal/interfaces/default_loaders/hst_cos.yaml
pyfocal/interfaces/default_loaders/keck_deimos.yaml
pyfocal/interfaces/loaders.py

Added YAML definition to support HST/COS and Keck/DEIMOS test data. Updated loader to this end.
This partially address #61

Added support for two other data formats

---

docs/source/api/index.rst
docs/source/api/loaders.rst
pyfocal/interfaces/default_loaders/kittpeak_mdm.yaml
pyfocal/interfaces/loaders.py

Recoded FITS loader to be more flexible. Added YAML for Kitt Peak MDM test data. Added API doc for loaders.
This fixes #61.

Support for Kitt Peak MDM data format

---

README.md
specviz/core/comms.py
specviz/interfaces/managers.py
specviz/ui/controller.py
specviz/ui/viewer.py
specviz/ui/widgets/sub_windows.py

Fixes:
* Some of #129 
* #131 
* #126

Presistence issues

---

specviz/core/containers.py
specviz/interfaces/managers.py
specviz/ui/controller.py
specviz/ui/viewer.py
specviz/ui/widgets/sub_windows.py

Addresses color issues in #129.

Color issues

---

specviz/analysis/statistics.py
specviz/core/comms.py
specviz/interfaces/managers.py
specviz/ui/controller.py
specviz/ui/qt/uic/source/mainwindow.ui
specviz/ui/viewer.py
specviz/ui/widgets/sub_windows.py

Fixes #129 plot updating issue. Fixes similar issue in #141.

Misc fixes

---

specviz/core/data.py

WCS: Read from CD first before trying CDELT

---

specviz/interfaces/loaders.py

Fix mask init in loader

---

specviz/core/data.py
specviz/interfaces/factories.py
specviz/interfaces/managers.py
specviz/ui/widgets/sub_windows.py

Further fixes #84 -- Traceback when user plot without opening a file first.
Fixes #167 -- Traceback when EW ROI is triggered on Anaconda/Qt4/RHEL6.

Fixes some traceback 

---

specviz/core/data.py
specviz/ui/controller.py

Fix traceback for improper mask

---

specviz/app.py

As mentioned in http://stackoverflow.com/questions/4938723/what-is-the-correct-way-to-make-my-pyqt-application-quit-when-killed-from-the-co

Catch KeyboardInterrupt and exit gracefully

---

docs/source/custom_loaders.rst

Added a disclaimer about YAML sensitivity in custom loaders doc.

Added a disclaimer about YAML sensitivity

---

specviz/core/linelist.py
specviz/data/linelists/Common_nebular.yaml
specviz/data/linelists/Common_stellar.yaml
specviz/interfaces/registries.py
specviz/ui/qt/uic/source/linelists.ui

The UI .py file is not being used yet. It was generated with QtCreator but will be refactored to conform to the new standard.

Fix bug with file type filter showing spectral line lists. Line list UI

---

setup.py
specviz/analysis/statistics.py
specviz/app.py
specviz/core/comms.py
specviz/core/data.py
specviz/external/glue/data_viewer.py
specviz/external/glue/viewer_options.py
specviz/plugins/data_list_plugin.py
specviz/plugins/layer_list_plugin.py
specviz/plugins/model_fitting_plugin.py
specviz/plugins/statistics_plugin.py
specviz/ui/widgets/sub_windows.py
specviz/ui/widgets/windows.py

* Moving the specviz glue viewer inside the specviz repo unintentionally made glue a dependency. Avoided this by checking for glue installations.
* Several layer mask issues were found when dealing with `ModelLayer` objects. Mainly, the parent ROI layer mask was being "baked" into the `ModelLayer` mask, and causing index issues.
* Small workflow improvements.

Various improvements

---

specviz/plugins/model_fitting_plugin.py

Fix truncation issue after a model is fit

---

specviz/analysis/models/gaussian_absorption.py
specviz/interfaces/factories.py
specviz/interfaces/initializers.py

This code supersedes the former pull request. Please disregard that one.

Better definition for an absorption Gaussian - remove RedshiftScaleFactor

---

specviz/analysis/filters.py
specviz/core/comms.py
specviz/core/threads.py
specviz/interfaces/registries.py
specviz/plugins/data_list_plugin.py

Addresses issues described in #275 and #274.

File loading and loader parsing bug fixes

---

specviz/plugins/data_list_plugin.py
specviz/plugins/layer_list_plugin.py
specviz/plugins/plot_tools_plugin.py
specviz/ui/widgets/dialogs.py

Fixes crashing to desktop when invalid unit is input. Also adds colored validation for unit input.

Fix unit crash bug, add validation

---

.travis.yml
docs/source/conf.py
docs/source/viewer.rst
requirements.txt
setup.cfg
setup.py
specviz/analysis/statistics.py
specviz/plugins/data_list_plugin.py

Travis is being difficult, using this PR to mess with settings.

Travis update

---

specviz/interfaces/model_io/py_model_io.py
specviz/interfaces/model_io/yaml_model_io.py
specviz/plugins/data_list_plugin.py
specviz/plugins/layer_list_plugin.py
specviz/plugins/model_fitting_plugin.py

Fixes https://github.com/spacetelescope/specviz/issues/288 - I tested what I could in the GUI but couldn't figure out how to trigger all of them.

Use qtpy.compat for file open/save dialogs

---

specviz/analysis/statistics.py
specviz/analysis/tests/test_statistics.py
specviz/interfaces/factories.py
specviz/plugins/statistics_plugin.py

Remove SLSQP as per discussions in sprint 6/7/2017
Add RMS, SN to real-time stats

Remove SLSQP fitter

---

docs/source/viewer.rst

Addresses #221 
Also some changed description of UI that appear to be out of data.

Add note about statistics with multiple ROIs

---

specviz/data/mask_definitions/jwst.ecsv
specviz/data/mask_definitions/sdss.ecsv
specviz/data/yaml_loaders/sdss_optical.yaml
specviz/io/yaml_loader.py
specviz/plugins/mask_editor_plugin.py

This PR adds Bit Mask support to the mask editor plugin.
Their are two mask description files one for SDSS, one for JWST.

Mask editor

---

specviz/data/qt/ui/wizard.ui
specviz/widgets/wizard.py

Note that the wizard code needs to be tidied up and commented, but I'm just focusing on getting the functionality in there first, and will do a tidy-up in a separate PR.
cc @mattjhill

Add support for selecting mask information in wizard

---

specviz/data/qt/ui/statistics_plugin.ui
specviz/data/qt/ui/wizard.ui
specviz/utils/parse_fits.py
specviz/widgets/wizard.py

This PR mainly fixes #323, but also improves padding on the statistics plugin, and renames the file wizard dialog.

Bug fix; visual tweaks

---

specviz/analysis/filters.py
specviz/analysis/statistics.py
specviz/analysis/utils.py
specviz/core/data.py
specviz/core/plots.py
specviz/core/threads.py
specviz/data/qt/ui/main_window.ui
specviz/data/qt/ui/model_fitting_plugin.ui
specviz/plugins/layer_list_plugin.py
specviz/plugins/mask_editor_plugin.py
specviz/plugins/model_fitting_plugin.py
specviz/plugins/statistics_plugin.py
specviz/third_party/glue/data_viewer.py
specviz/widgets/axes.py
specviz/widgets/dialogs.py
specviz/widgets/linelists_window.py
specviz/widgets/sub_windows.py
specviz/widgets/windows.py

Fixed layer arithmetic issues.

Arithmetic bug fixes

---

specviz/interfaces/factories.py

Update wayward model name

---

specviz/third_party/glue/data_viewer.py

Fixes issue with changing default spectrum data views.

Fix glue viewer

---

specviz/third_party/glue/data_viewer.py

fixed errant colon

---

specviz/third_party/glue/data_viewer.py

If multiple datasets were present, there was one SubsetCreatedMessage per dataset, but we should only listen to ones for which a data layer is already present in Specviz. Furthermore, if a subset was defined in another dataset, ``to_mask`` fails with an IncompatibleAttribute error (this is expected behavior) and so we need to make sure we catch this and set the mask to be empty.
This came up while doing some development on cubeviz.

Improvements to subset event handlers

---

specviz/core/plots.py
specviz/third_party/glue/data_viewer.py
specviz/widgets/sub_windows.py

There were several requests to make the plot lines thicker as they are hard to see in the cubeviz window. I think it might make sense here if you are good with it. I also made the green line, that represents the spatial slice location, thicker as it was hard to see.

Thicker plot lines and thicker slider line

---

specviz/widgets/dialogs.py

I needed to receive a message in cubeviz that there was a change in redshift Z.  (If there is a better way to do this, please post, I'll fix.)
This works for the cubeviz stuff, not sure if it will break other specviz stuff.

Pass message back out if there is a change

---

specviz/third_party/glue/viewer_options.py

This should also be compatible with the current stable version of glue as the functionality I use now has been around for a few versions.
Fixes #379

Fix compatibility with latest developer version of glue

---

specviz/core/linelist.py
specviz/interfaces/loaders.py
specviz/io/yaml_loader.py
specviz/utils/parse_ecsv.py
specviz/widgets/linelists_window.py
specviz/widgets/sub_windows.py
specviz/widgets/wizard.py

Augment wizard to support ASCII and ECSV tables.

---

setup.cfg
specviz/core/plots.py
specviz/data/qt/ui/layer_list_plugin.ui
specviz/data/qt/ui/mask_editor_plugin.ui
specviz/data/qt/ui/model_fitting_plugin.ui
specviz/io/loaders/generic_loader.py
specviz/plugins/layer_list_plugin.py
specviz/plugins/mask_editor_plugin.py
specviz/plugins/model_fitting_plugin.py
specviz/plugins/tool_tray_plugin.py

- Ensure unit changes are propagated to plots.
- Fix simple writer for layer export.
- Disable unused tooling for now.
- Convert mask plugin to use .ui files.
- Model editor fixes.

Various usability fixes

---

specviz/core/items.py
specviz/core/models.py
specviz/data/ui/main_window.ui
specviz/data/ui/model_editor.ui
specviz/data/ui/plot_window.ui
specviz/data/ui/statistics.ui
specviz/widgets/custom.py
specviz/widgets/main_window.py
specviz/widgets/plotting.py
specviz/widgets/workspace.py

- Supports ROI adding/removing and on-plot information about bounds.
- Behavioral changes to show/hide of plugins
- Improvements to proxy model handling
- Improvements to loading and displaying data

New core changes and plotting improvements

---

specviz/core/items.py

The line width works but not the zorder - @nmearl, do you have any ideas why that might be?

Add the ability to customize the line width and zorder

---

specviz/widgets/workspace.py

This fixes the error `AttributeError: type object 'ViewMode' has no attribute 'TabbedView'` that was blocking work. I *believe* this is the correct fix, but it works for now and can be confirmed later.

Fixed TabbedView error

---

specviz/widgets/workspace.py

Add current software version to title bar

---

setup.cfg

We now require astropy>=3.0

---

specviz/plugins/smoothing/smoothing_dialog.py

The smoothing GUI appears to be created when specviz is first started. Then each time the user wants to smooth the GUI is displayed.  The UI loading (from the .ui file) was happening each time the user was displaying the GUI but should only happen once. 
The code was slightly re-organized so the loading of the UI and displaying are separated.
Huge help from @drdavella 
Fixes https://github.com/spacetelescope/specviz/issues/481
Fixes https://github.com/spacetelescope/specviz/issues/495

Re-worked loading and display of smoothing gui

---

specviz/conftest.py
specviz/tests/test_specviz_gui.py

Opens specviz_gui using pytest. Might be redundant with Dan's most recent PR.

Specviz gui tests

---

specviz/core/hub.py
specviz/plugins/model_editor/items.py
specviz/plugins/model_editor/model_editor.py
specviz/plugins/model_editor/model_editor.ui
specviz/plugins/model_editor/models.py

Disallow interaction until user has created a model

---

specviz/conftest.py
specviz/core/plugin.py
specviz/plugins/arithmetic/arithmetic_editor.py
specviz/plugins/arithmetic/tests/test_arithmetic_gui.py
specviz/widgets/workspace.py

This partially addresses #542. It also fixes a minor bug, although more discussion might be required with @mfixstsci and @nmearl.
I hope that this serves as a good template for additional testing.
@nmearl as you can see here I actually added a pointer to the plugins in the workspace in order to facilitate testing. The change we made in #534 was useful, but creating a new instance of a plugin has the side effect of adding another icon to the toolbar, which I'd like to avoid. I think what I've done here is reasonable, though.

Add basic test for arithmetic gui

---

specviz/core/hub.py
specviz/core/items.py
specviz/plugins/model_editor/__init__.py
specviz/plugins/model_editor/continuum_generator.py
specviz/plugins/model_editor/model_editor.py
specviz/plugins/model_editor/models.py
specviz/plugins/smoothing/smoothing_dialog.py
specviz/widgets/plotting.py
specviz/widgets/workspace.py

Added a new operation that will auto-generate a continuum data item and associated model for a given spectrum.
Related to #573 and #533.

Auto generate continuum

---

specviz/widgets/workspace.py

Restore Spectrum1D import that was lost during rebase

---

specviz/plugins/loader_wizard/loader_wizard.py

Populate loader save name; disallow duplicates in registry

---

specviz/plugins/model_editor/model_editor.ui

Adds a label to the data selection box in the model editor.

Add label to model editor data selector

---

specviz/plugins/model_editor/initializers.py
specviz/plugins/model_editor/model_editor.py
specviz/plugins/model_editor/models.py

This re-introduces @ibusko's model initializer code. The initializer code in specutils needs to be built out more before it can be used here.

Introduce simple model initializations

---

specviz/core/models.py
specviz/widgets/plotting.py

Fixes issue where the property was not properly being resolved on an internal NoneType retrieval.

Fix #592: improper property error handling

---

specviz/widgets/workspace.py

This fixes #615. It supersedes #491.

Make "Auto (*)" the default loader in open data dialog

---

specviz/app.py
specviz/widgets/ui/splash_non_modal.ui

Add specutils version to splash screen

---

specviz/widgets/tests/test_workspace.py
specviz/widgets/workspace.py

This resolves #635. It also adds a test.

Fix bug that occurred when exporting data set

---

specviz/plugins/model_editor/model_editor.py
specviz/widgets/ui/workspace.ui
specviz/widgets/workspace.py

i reopen this pull request as i messed up to much in previous merge :/

don't crash on new model with no selected item

---

specviz/plugins/model_editor/continuum_generator.py
specviz/plugins/model_editor/model_editor.py

Fix ROIs in model generation; fixes #604 and #602

---

specviz/plugins/smoothing/smoothing_dialog.py
specviz/third_party/glue/operation_handler.py
specviz/third_party/glue/tests/test_viewer.py
specviz/third_party/glue/threads.py
specviz/third_party/glue/viewer.py

This PR fixes:
- Propagation of unit information (#679) 
- Deletion of plotted items on subset deletion

Glue data viewer improvements

---

specviz/third_party/glue/viewer.py

Part of the spacetelescope/cubeviz#484 PR.

Include data viewer interface for unit changing

---

README.rst

Directed users to Jdaviz in case they end up here via e.g. Google searching

Added note pointing to Jdaviz as the maintained repo

---

README.rst
docs/api.rst
docs/arithmetic-layer.rst
docs/developer.rst
docs/exporting.rst
docs/index.rst
docs/installation.rst
docs/launching.rst
docs/line_labels.rst
docs/loading_data.rst
docs/model_fitting.rst
docs/operations.rst
docs/regions.rst
docs/statistics.rst
docs/unit_conversion.rst
docs/workspaces_and_plots.rst

Adds Deprecation warning to all docs pages

Add Deprecation Warning to Docs
