spacetelescope/specviz

- pyfocal/interfaces/loaders.py
ASCII loader now handles missing columns in data. This fixes #46.
> ASCII loader now handles missing columns in data

- docs/source/api/data.rst
- docs/source/custom_loaders.rst
- pyfocal/app.py
- pyfocal/core/data.py
- pyfocal/interfaces/default_loaders/ascii.yaml
- pyfocal/interfaces/factories.py
- pyfocal/interfaces/loaders.py
- pyfocal/interfaces/managers.py
- pyfocal/ui/controller.py
Changes include:
* Fixes #46 which requires
* Unit assumptions for ASCII data when units are not explicitly set (say, by IPAC).
*  Loaders to auto set flux uncertainty to zeroes (instead of `None`) when data has no uncertainty column to avoid crashing down the line.
* Updated doc for custom loader to reflect code changes.
* Added API doc for `core.data` module.
* `pyfocal filename` can how handle both FITS and ASCII sys arg input. Still no wildcard support.
* Replace some `print()` functions with more elegant logging calls.
> Bug fix, doc, code clean up

- docs/source/installation.rst
This adds a "Known Issues" section to the installation docs with a quick fix for the "this application failed to start because it could not find or load the Qt platform plugin "cocoa"." error
> Add "Known Issues" section with workaround for qt4/qt5 error

- docs/source/custom_loaders.rst
- pyfocal/interfaces/default_loaders/keck_deimos.yaml
- pyfocal/interfaces/loaders.py
- pyfocal/interfaces/registries.py
Fixed circular import in loaders/registries so API doc will build. Added wavelength unit info in Keck/DEIMOS YAML. Clarified custom loaders in doc.
> Doc fixes, Keck/DEIMOS YAML update

- pyfocal/interfaces/model_io.py
- pyfocal/ui/controller.py
- pyfocal/ui/qt/uic/source/mainwindow.ui
- pyfocal/ui/viewer.py
These are the non-UI files, plus the main window.ui file. I found I can't run gen_uic.sh reliably; it generates errors in the resulting .py files (such as missing EOL characters). I also got merge errors in the .ui files that I couldn't fix. Could it be that I am running a slightly different version of QT Designer than required? (mine is 5.5)
So I think we have to merge this pull request first. That won't harm the existing code since the new UI won't be in place, so no buttons to access the new functionality will be visible. Once the merge is done, we can try to run gen_uic and deal with its issues separately.
> Adding (again...) 'model saving to file' functionality.

- docs/source/installation.rst
I think these instructions were written when the name was ``pyfocal`` - this just changes the name used for the conda environment to be more like ``specviz``.
> Update conda install instructions to be better-aligned to specviz name

- requirements.txt
This changes the requirements.txt file to call for using the release version instead of ``nmearl/astropy``. We can put in a specific version if that's better, but if there was a specific reason why specviz needs the *dev* version of astropy, I can instead modify this to point to ``astropy/astropy`` instead of ``nmearl/astropy``.  Better yet, if we can point to a specific *commit*, that's even better.
> Change astropy to release version

- setup.py
Without this, specviz doesn't work when doing a clean install
> Added missing entry for linelists in package_data

- setup.py
Fix ConfigParser compatibility with Python 3. Fixes #212 .
> Fix ConfigParser compatibility with Python 3

- README.md
- docs/source/installation.rst
- docs/source/model_fitting.rst
- setup.cfg
- setup.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- specviz/core/plots.py
scatterplots and histograms wouldn't change.  the 'is' needed to be replaced with '==' in the comparisons
> fix scatterplot and histogram bugs

- specviz/app.py
- specviz/external/glue/__init__.py
- specviz/external/glue/data_viewer.py
- specviz/external/glue/viewer_options.py
Note that this will require glue-core 0.10.2 to be released, which I'll try and do this evening (in the mean time this requires the developer version of glue).
One thing that is weird is that if I open a table with 3 entries, when adding the dataset to the specviz viewer, ``on_file_read`` is called three times, but then only one spectrum appears in the data collection in specviz.
> Fix compatibility with glue 0.10.x

- specviz/analysis/models/blackbody.py
- specviz/interfaces/factories.py
This is a temporary change for the upcoming Fool's release. Will be reverted when the code that calls the black body initializer and evaluate methods gets fixed.
> Temporarily hide the black body model

- specviz/core/data.py
This is hacky but not dangerous - it will make sure things don't crash with the current stable version of specutils and the latest developer version of Astropy.
> Fix Travis build with Astropy dev

- specviz/utils/parse_fits.py
This fixes the issue with ``generic_spectra.fits`` which was to do with the fact that HDU 1 had no name (which is fine).
@nmearl @kassin - the ``generic_spectra.fits`` file also contains pseudo-WCS in HDU 0, but this is incomplete:
```
CUNIT1  = 'Angstrom'                                                            
CRVAL1  =                200.0                                                  
CDELT1  =                  1.0                                                  
```
specifically, CTYPE1 is missing, so astropy WCS doesn't recognize this as being a spectral WCS. Is this a fake spectrum file, or was it found in the wild?
> Fix loading of HDUs with no name

- specviz/plugins/layer_list_plugin.py
An issue with astropy helpers was leading to a dreaded error message `ImportError: parent 'specviz' not in sys.modules` when attempting to use `pip` to install SpecViz, this update solves that. Also, attempting to use the color changer would crash SpecViz due to the widget not having been imported.
> Updates astropy helpers and fixes widget import

- specviz/utils/parse_fits.py
This covers a corner case (e.g. with COS spectrum files from the MAST archive) wherein the fits arrays are cut up into two parts, each covering one of the two separate detectors.
This follows the mold of the custom loader where the data arrays are flattened.
> Improve wizard with disparate detector chips data structures

- setup.cfg
- specviz/core/data.py
- specviz/data/qt/ui/model_fitting_plugin.ui
- specviz/plugins/model_fitting_plugin.py
The previous locking behavior has columns shared between name and check state; separate them, so the icon represents only when checkable column is clicked.
> Fix param locking behavior

- specviz/app.py
- specviz/data/qt/ui/main_window.ui
- specviz/third_party/glue/data_viewer.py
- specviz/widgets/windows.py
At the moment, when using specviz as part of cubeviz, specviz's menu overrides glue's menu (this doesn't happen when using specviz as a standalone plugin in glue). The only clean way to avoid this is to add an option to not construct the menubar in the first place rather than trying to remove it after creation.
> Properly disable menubar when using specviz in glue plugin mode

- specviz/plugins/model_fitting_plugin.py
This change fixes an installation error on Windows (`HOME` is not generally defined).
See full log output here:
https://ci.appveyor.com/project/spacetelescope/cubeviz/build/1.0.58/job/827djd5wbuvgqls8
Log snippet:
```python
Running setup.py install for specviz: finished with status 'error'
Complete output from command C:\conda\envs\test\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-build-cmocdxzw\\specviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\appveyor\AppData\Local\Temp\1\pip-dd3p7ngu-record\install-record.txt --single-version-externally-managed --compile:
INFO:root:Added APOGEE apVisit to loader …
```
> Detect home directory in a portable way

- specviz/widgets/sub_windows.py
The 'Pos:' was not being updated on the bottom toolbar when the mouse is moved around the screen. It appears to have just been a conditional check as the `index` value is == 0 in the normal case.  This fix works in the third_party glue attachment in cubeviz.
> Fix to show position update

- specviz/data/linelists/SDSS-IV.list
- specviz/data/linelists/SDSS-IV.yaml
This PR adds the spectral lines that are used by the SDSS-IV Science Archive Webapp (SAW).  See *e.g.* https://dr14.sdss.org/optical/spectrum/view?run2d=v5_10_0&plateid=4055&mjd=55359&fiberid=596&action=search
Among other things, this will allow easy comparisons of spectral line display functionality.
> Add SDSS-IV linelists

- specviz/core/models.py
In ``PlotProxyModel.item_from_index``, ``PlotDataItem``s get created if needed - this extends the same logic to ``PlotProxyModel.item_from_id``. I'm not 100% sure if this is correct, so opening this as a standalone PR to make sure it's not buried in some other changes.
> Create PlotDataItem in item_from_id if it doesn't already exist

- MANIFEST.in
- setup.py
I had a problem installing from the git master because it doesn't install the UI files.  This PR updates setup.py and MANIFEST.in to fix the issue. Check the extra lines at the bottom of the MANIFEST.in file to make sure you really want them - I went ahead and ran `check-manifest` just to see what was left out.
Minimally, `recursive-include specviz *.ui` and adding `install_package_data=True` to the setup are needed, but I'm not sure about the others. 
If this PR is in error, feel free to close!
> Update MANIFEST.in and setup.py to install tracked files

- specviz/app.py
- specviz/third_party/glue/viewer.py
- specviz/widgets/workspace.py
This is fairly minor issue, but since it's part of the API, it should probably be fixed.
Also, since it is part of the API, I'm not sure whether we need to maintain some kind of backwards compatibility here.
> Fix spelling of embedded in API

- specviz/third_party/glue/tests/test_utils.py
- specviz/third_party/glue/tests/test_viewer.py
Set the third_party tests to xfail for now as they are failing and it is not clear why they are failing.
This will have to be reverted in a future PR when the tests are corrected.
> xfailed the tests for now

- specviz/plugins/statistics/statistics_widget.py
There was an error in the code when updating the lower or upper bound of a SpectralRegion. This is not possible in the new code.  The code was re-factored to create a new SpectralRegion object instead. Works locally.
Fixes https://github.com/spacetelescope/specviz/issues/467
> Fix for SpectralRegion stats calculation

- specviz/widgets/plotting.py
The default region size was not being calculated quite right. I re-worked the calculation and now the default region size fits within the displayed region.
E.g., 
Fixes: https://github.com/spacetelescope/specviz/issues/475
> Reworked the default region size

- setup.cfg
This should fix #464 - this is actually an "aspirational" requirement because I'm not sure it's currently true... but I know some of the current/near-term PRs will require it.
> specify specutils version

- specviz/core/items.py
- specviz/widgets/ui/workspace.ui
The maximum width of the list view (where the data color and names show) was set to 250. This was removed (the default is still narrow) so now people can increase the width to see the full data names.
I also added a tooltip based on the name so one can hover on the data name to see what it is if the width is still narrow.
Fixes https://github.com/spacetelescope/specviz/issues/494
> added tooltip and removed max width

- specviz/third_party/glue/tests/test_utils.py
- specviz/third_party/glue/tests/test_viewer.py
- specviz/third_party/glue/utils.py
For reasons I don't fully understand, the construction of Spectrum1D in the glue plugin was changed in https://github.com/spacetelescope/specviz/pull/456. However, this doesn't work properly because of a bug in specutils (https://github.com/astropy/specutils/issues/369).
This PR re-instates the old way of doing this, and also fixes ``glue_data_has_spectral_axis`` for glue Data objects that don't have WCS coordinates.
> Fix glue plugin tests and functionality

- specviz/third_party/glue/tests/test_utils.py
- specviz/third_party/glue/utils.py
Currently, the specviz plugin for glue requires ``Data`` objects to have their ``coords`` attribute be a ``WCSCoordinates`` object. This means that we can't use the plugin for spectra which have spectral coordinates defined by a lookup table. This PR adds a ``SpectralCoordinates`` subclass of ``Coordinates`` which can be used to easily make glue ``Data`` objects that have a lookup table for the spectral coordinates, and can then be used inside specviz in glue. Creating such a data object is easy:
```python
>>> coords = SpectralCoordinates([1000, 1200, 1400] * u.AA)
>>> data = Data(label='1D Spectrum', coords=coords)
>>> ...
```
> Added a SpectralCoordinates class for glue plugin

- specviz/core/plugin.py
This stores a simple reference to a plugin action's parent plugin object class so that it can be accessed via the gui testing functions.
> [WIP] Store reference to plugin in tool bar actions

- specviz/core/plugin.py
- specviz/widgets/workspace.py
This adds a reference in the workspace to the plugin bars purely for the purposes of enabling testing of these plugins.
> Minor change to enable testing of stats and model editor plugins

- .travis.yml
This is causing failures on multiple PRs now. Since we don't even have coverage set up for this repository, let's disable this test for the time being.
> Disable coverage test for now.

- specviz/plugins/model_editor/model_editor.py
- specviz/plugins/model_editor/models.py
Previously, removing a model resulted in an invalid arithmetic equation which would prevent the user from being able to fit the model again until they fixed it. There was no feedback about why clicking the fitting button didn't work properly.
This PR adds some regex to auto-remove the model name from the arithmetic equation and if the new equation is invalid, will force open the arithmetic editor so that the user can fix the equation.
> Model fitting improvements

- specviz/plugins/model_editor/items.py
- specviz/plugins/model_editor/model_editor.py
- specviz/plugins/model_editor/models.py
Model editor's `Fixed` column crashes when the checkbox is clicked. This PR fixes this bug. I also added "Plot Units" to every unit display in the model editor param box. Lastly, I made sure that the model editor redraws a plot only if the selected `plot_data_item` is of type `ModelDataItem`.
> Model Editor Checkbox Fix

- docs/index.rst
- specviz/conftest.py
- specviz/plugins/model_editor/model_editor.py
- specviz/plugins/model_editor/model_editor.ui
- specviz/plugins/model_editor/models.py
- specviz/plugins/model_editor/tests/test_models.py
Currently this just uses `pickle` for simplicity, but it should be easy to adapt for other output formats.
This resolves #516.
Also, this is based on #543 and will need to be rebased once that is merged.
> Add model saving and loading

- specviz/plugins/model_editor/model_advanced_settings.ui
- specviz/plugins/model_editor/model_editor.py
- specviz/plugins/statistics/statistics_widget.py
This PR introduces the following:
1) Stat widget listens to data changes via `itemChanged` signals.
2) Option to set the number of sig figs as discussed in #558 :
> Connect Stats to Model and Display Digit Patch

- specviz/core/items.py
- specviz/core/models.py
- specviz/plugins/arithmetic/arithmetic_editor.py
- specviz/widgets/plotting.py
Fixes an incompatibility checking issue that allowed unitless spectrum objects to go enabled even when they should be disabled.
Fixes #550.
> Force checking on all added model items

- specviz/plugins/statistics/statistics.ui
- specviz/plugins/statistics/statistics_widget.py
- specviz/plugins/statistics/tests/test_statistics_gui.py
- specviz/widgets/workspace.py
This PR introduces the following 
- Closes #572 : Add combo box to select stats type as discussed in #572 
- Adds `plot_window_activated` signal that fires when a new plot sub-window is opened. This fixes the lag that occurs when moving an ROI. i.e: the signal I used previously to listen to plot window activations was also firing for other events.
- Update the ROI info box to indicate that its stats over a single ROI. Improve range labels of the ROI.
> Statistics Type Selection

- specviz/widgets/workspace.py
This builds on the work done in https://github.com/astropy/specutils/pull/381 in order to allow files that contain multiple heterogenous spectra to be loaded.
This PR should not be merged until the above PR in `specutils` is accepted and merged. Also I need to add some tests here. I plan to create mock data files on the fly and simply test the backend loader functionality (i.e. ignoring the UI).
Also this will need to be rebased on #527 once it is reviewed and merged.
> Load multiple spectra from a single file

- specviz/plugins/model_editor/continuum_generator.py
Fixes the issue of continuum model fitting using excluded regions instead of included regions. Requires astropy/specutils#403.
> Use inclusions regions in continuum generator

- .travis.yml
- docs/installation.rst
- setup.cfg
- setup.py
- specviz/__init__.py
It appears that `specutils` will only be supporting Py36 and later going forward, and I believe that the same is true of the latest version of Astropy, so this seems like a prudent move. We were also encountering issues with Py35 on travis which seemed to indicate incompatible dependencies
> Drop support for py35, update travis matrix

- .travis.yml
- specviz/tests/test_load_data.py
- specviz/widgets/workspace.py
This resolves #608.
So obviously this took a lot less effort than I originally anticipated, but that's mostly because @SaOgaz had done all of the legwork of gathering the relevant test data and setting it up on Box.
Right now the test simply loads each data file into `specviz` and makes sure that nothing goes wrong. It's possible that we want to add more comprehensive checks to the tests, but I think this is actually a pretty good smoke test for now.
Each test case starts up a new instance of `specviz` in order to make sure we're simulating something like a real user workflow. In order to avoid the Qt segfault issue we discussed earlier in the week, each test case runs `specviz` in a separate process using the `multiprocessing` module. This might be worth using for other test cases as …
> Add tests for loading JWST data

- specviz/app.py
- specviz/widgets/workspace.py
This change allows data loader errors to be handled consistently (by displaying the error message in a pop-up dialog) both when loading from the GUI and when loading a file from the command line.
> Handle data loader errors consistently

- .travis.yml
- setup.cfg
- specviz/tests/test_load_data.py
- specviz/widgets/workspace.py
This resolves #618. It is based on #639, which should be merged first. It also depends on a bug fix in `specutils` (see https://github.com/astropy/specutils/pull/440), so the tests will not pass until that is merged and released.
There were three fundamental problems here:
1. Most `specutils` loaders for `SpectrumList` were not providing identifiers. This was a bug and meant that if a user specified the wrong loader, even for a valid data file, the file would be opened but would likely cause a crash somewhere later. This is no longer possible with the `specutils` fix mentioned above.
2. In certain cases, `specviz` was not using identifiers to check whether a particular loader should be used before trying to attempt the file. Now that `specutils` provides identifiers for most cases, they …
> Make data loader handling more correct/robust

- docs/developer.rst
- specviz/app.py
- specviz/tests/test_load_data.py
- specviz/widgets/spectrum_selection.py
- specviz/widgets/tests/test_spectrum_selection.py
- specviz/widgets/ui/spectrum_selection.ui
- specviz/widgets/workspace.py
This resolves #609. It provides a dialog that enables users to select which spectra to load from a file that contains multiple spectra.
This is pretty basic at the moment. We may want to consider adding a preview in the future. Also, it would eventually be useful for `specutils` loaders to provide more informative metadata about spectra (probably derived from the HDU headers) so that we could give more informative names to these data items.
The same open file dialog is used:
However, when loading a file with multiple spectra, users now see the following dialog after clicking "Open":
By default, all spectra are selected, so most users can just click "Open" and keep moving.
> Add dialog for selecting which spectra to load

- specviz/plugins/arithmetic/arithmetic_editor.py
This resolves #633. Feel free to suggest a better name.
> Use fake data name for examples in arithmetic editor

- .travis.yml
- specviz/tests/test_load_data.py
- tox.ini
The motivation for this is that it allows for push-button replication of CI test environments locally. In order to run the tests using `tox` locally, it is necessary to have a `conda` environment with both `tox` and the `tox-conda` plugin installed (which are both currently only available from `pypi`).
> Use tox for testing

- setup.cfg
We have not update the qt version of specviz to be compatible with the latest astropy. This PR pins the versions to the current realm of tested dependencies.
> Pin dependency versions to maintain compatibility
